language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

sudo: false

matrix:
  fast_finish: true

install:
  - composer ci-build

script:
  - composer test

cache:
  files:
    - composer.lock
  directories:
    - $HOME/.composer
    - vendor
