language: php
php:
  - '5.5'
  - '5.6'

sudo: false
install:
  - composer require "symfony/symfony:${SYMFONY_VERSION}"
script:
  - ./vendor/bin/phpunit
  - composer run-script behat
env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.*
cache:
  files:
    - composer.lock
  directories:
    - $HOME/.composer
    - vendor

